Feature/dashboard popup
KarmaKamikaze/HotelPriceScout pull request #232
Opened 2021-11-25 14:12 UTC by WassawRoki

i need feedback on names and shit

2021-11-25 14:22 UTC, selectionator approved these changes
Der skal bare lige rettes fra WarningMessadge til WarningMessage. Men ellers super 👍

2021-11-25 14:22 UTC, selectionator commented on HotelPriceScout/Data/Interface/Dashboard.cs
> +        public List<WarningMessagde> WarningMessagde { get; set; } = new List<WarningMessagde>();
WarningMessage*

2021-11-25 14:22 UTC, selectionator commented on HotelPriceScout/Data/Interface/IDashboard.cs
> +        List<WarningMessagde> WarningMessagde { get; set; }
WarningMessage*

2021-11-25 14:22 UTC, selectionator commented on HotelPriceScout/Data/Interface/WarningMessagde.cs
> +    public class WarningMessagde
WarningMessage*

2021-11-25 14:22 UTC, selectionator commented on HotelPriceScout/Data/Interface/WarningMessagde.cs
> +        public WarningMessagde( string listOfWarnings, string bookingSite)
WarningMessage*

2021-11-26 18:48 UTC, Sarmisuper requested changes
lgtm udover de kommentarer jeg har lagt

2021-11-26 18:48 UTC, Sarmisuper commented on HotelPriceScout/Data/Interface/Dashboard.cs
> +            string bookingSitename = bookingSite.Name;
unused

2021-11-26 18:48 UTC, Sarmisuper commented on HotelPriceScout/Data/Interface/Dashboard.cs
> +            //WarningMessagde.Add(new WarningMessagde("Date: 21/02/2021 hotel: Phønix, with roomtype: 4|Date: 21/02/2021 hotel:Cabin, with roomtype: 1|Date: 21/02/2021hotel:Sarmilan, with roomtype: 2
zombie

2021-11-26 18:48 UTC, Sarmisuper commented on HotelPriceScout/Data/Interface/WarningMessagde.cs
> +        public string ListofWarnings { get { return listOfWarnings; } set { listOfWarnings = value; } }
hold up. Her skal du bare have de to øverste og så starte dem med stort.

2021-11-26 18:48 UTC, Sarmisuper commented on HotelPriceScout/HotelPriceScout.csproj
> -    </ItemGroup>
this is weird

2021-11-26 18:48 UTC, Sarmisuper commented on HotelPriceScout/Pages/DashboardPage.razor
> +
remove empty lines

2021-11-26 18:48 UTC, Sarmisuper commented on HotelPriceScout/Pages/DashboardPage.razor
> +
remove empty line

2021-11-26 18:48 UTC, Sarmisuper commented on HotelPriceScout/Pages/DashboardPage.razor
> +        string[] hest = item.ListofWarnings.Split("|");
mangler ordentligt navn

2021-11-26 18:48 UTC, Sarmisuper commented on HotelPriceScout/Pages/DashboardPage.razor
> +        // Also tried _cards.RemoveAll(i => i.TitleElementId == card.TitleElementId);
zombie

2021-11-26 18:48 UTC, Sarmisuper commented on HotelPriceScout/Pages/DashboardPage.razor
> +                //Dashboard.UpdateUiMissingDataWarning(Program.ScoutSharedService.Scout.BookingSites.First());
zombie zombie monki monki

2021-11-29 09:21 UTC, merged